name: UFEMISM Test Suite - compile and cache UFEMISM
run-name: ${{ github.actor }} - UFEMISM Test Suite - compile and cache UFEMISM
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compile_UFEMISM:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran
          brew info petsc

      - name: Set up Fortran compiler          # See: https://github.com/marketplace/actions/setup-fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Verify compiler setup
        run: gfortran --version

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Compile UFEMISM
        run: ./compile_clean_mac.csh

      - name: Cache UFEMISM program            # TijnB: caching is quite slow, and not optimal here since
        uses: actions/cache/save@v3            # we assume the model code will be changed whenever this workflow
        id: UFEMISM_program_cache_save         # is run, so we need to recompile the code anyway.
        with:                                  # So: use artifacts instead!
          path: UFEMISM_program
          key: UFEMISM_program_${{ github.ref_name }}_${{ github.run_id }}
