# The full UFEMISM Test Suite

name: UFEMISM Test Suite
run-name: ${{ github.actor }} - UFEMISM Test Suite
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile_and_cache_UFEMISM:
    uses: ./.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM.yml

  run_unit_tests:
    needs: compile_and_cache_UFEMISM
    uses: ./.github/workflows/UFE_test_suite_run_unit_tests.yml

  analyse_unit_tests:
    needs: run_unit_tests
    uses: ./.github/workflows/UFE_test_suite_analyse_unit_tests.yml

  run_component_tests:
    needs: compile_and_cache_UFEMISM
    uses: ./.github/workflows/UFE_test_suite_run_component_tests.yml

  analyse_component_tests:
    needs: run_unit_tests
    uses: ./.github/workflows/UFE_test_suite_analyse_component_tests.yml
