# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated tests
on:
  workflow_call:

jobs:

  integrated_tests_idealised_Halfar_dome_Halfar_10km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_10km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_20km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_20km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_40km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_40km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_5km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_5km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_static_10km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_10km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_static_20km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_20km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_static_40km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_40km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_static_5km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_5km.yml

  integrated_tests_idealised_ISMIP-HOM_exp_A:
    uses: ./.github/workflows/zz_integrated_tests_idealised_ISMIP-HOM_exp_A.yml

  integrated_tests_idealised_MISMIP_mod:
    uses: ./.github/workflows/zz_integrated_tests_idealised_MISMIP_mod.yml

  integrated_tests_idealised_MISMIPplus:
    uses: ./.github/workflows/zz_integrated_tests_idealised_MISMIPplus.yml

  integrated_tests_realistic_Antarctica_initialisation_Ant_init_20kyr_invBMB_invpwf_40km:
    uses: ./.github/workflows/zz_integrated_tests_realistic_Antarctica_initialisation_Ant_init_20kyr_invBMB_invpwf_40km.yml
