name: UFEMISM Test Suite - run component tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - run component tests
on:
  workflow_call:

jobs:
  run_component_tests:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --remote

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_dev_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run component tests
        run: mpiexec  -n 2  UFEMISM_program  component_tests

      - name: Upload output as artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: results_component_tests
          path: automated_testing/component_tests/results