# The full UFEMISM Test Suite

name: UFEMISM Test Suite
run-name: ${{ github.actor }} - UFEMISM Test Suite
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Compile the model and cache the executable
  compile_and_cache_UFEMISM:
    uses: ./.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM.yml

  # Install and cache Matlab
  install_and_cache_Matlab:
    uses: ./.github/workflows/UFE_test_suite_install_and_cache_Matlab.yml

  # Run the unit tests and analyse the results
  run_unit_tests:
    needs: [compile_and_cache_UFEMISM, install_and_cache_Matlab]
    uses: ./.github/workflows/UFE_test_suite_run_unit_tests.yml

  analyse_unit_tests:
    needs: run_unit_tests
    uses: ./.github/workflows/UFE_test_suite_analyse_unit_tests.yml

  # Run the component tests and analyse the results
  run_component_tests:
    needs: [compile_and_cache_UFEMISM, install_and_cache_Matlab]
    uses: ./.github/workflows/UFE_test_suite_run_component_tests.yml

  analyse_component_tests:
    needs: run_component_tests
    uses: ./.github/workflows/UFE_test_suite_analyse_component_tests.yml

  # Run the integrated tests and analyse the results
  run_and_analyse_integrated_tests:
    needs: [compile_and_cache_UFEMISM, install_and_cache_Matlab]
    uses: ./.github/workflows/UFE_test_suite_run_and_analyse_integrated_tests.yml

  # DENK DROM - fix this!
  # # Append the temporary scoreboard files from the component and integrated tests
  # # to the main scoreboard files, and commit the changes
  # finalise_scoreboard:
  #   needs: [analyse_component_tests, run_and_analyse_integrated_tests]
  #   uses: ./.github/workflows/UFE_test_suite_finalise_scoreboard.yml
