# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated tests
on:
  workflow_call:

jobs:

  integrated_tests_idealised_Halfar_dome:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome.yml

  # integrated_tests_idealised_ISMIP-HOM:
  #   uses: ./.github/workflows/zz_integrated_tests_idealised_ISMIP-HOM.yml

  integrated_tests_idealised_MISMIP_mod:
    uses: ./.github/workflows/zz_integrated_tests_idealised_MISMIP_mod.yml

  integrated_tests_idealised_MISMIPplus:
    uses: ./.github/workflows/zz_integrated_tests_idealised_MISMIPplus.yml

  integrated_tests_idealised_SSA_icestream:
    uses: ./.github/workflows/zz_integrated_tests_idealised_SSA_icestream.yml

  integrated_tests_realistic_Antarctica_initialisation_Ant_init_20kyr_invBMB_invfric_40km:
    uses: ./.github/workflows/zz_integrated_tests_realistic_Antarctica_initialisation_Ant_init_20kyr_invBMB_invfric_40km.yml
