# Clean up the UFEMISM Test Suite scoreboard

name: UFEMISM Test Suite - weekly scoreboard clean-up
run-name: ${{ github.actor }} - UFEMISM Test Suite - weekly scoreboard clean-up
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 1'   # Every Monday at 04:00h

jobs:

  clean_up_scoreboard:
    runs-on: macos-latest
    steps:

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0

      - name: Clean up scoreboard
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/scoreboard/scripts')
            delete_old_scoreboard_files('${{github.workspace}}/automated_testing')

      - name: Commit deleted scoreboard files
        # See https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: automated_testing/scoreboard/scoreboard_files/*.xml
          author_name: ${{ github.actor }} (from UFEMISM scoreboard clean-up workflow)
          message: 'Clean up scoreboard files (from weekly UFEMISM scoreboard clean-up workflow)'
          push: true