name: UFEMISM Test Suite - analyse component tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - analyse component tests
on:
  workflow_call:

jobs:
  analyse_component_tests:
    runs-on: macos-latest
    steps:

      - name: Checkout UFEMISM repository (from pull request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
         repository: ${{ github.event.pull_request.head.repo.full_name }}
         ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout UFEMISM repository (from manual run)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4

      - name: Download component test results as artifacts
        uses: actions/download-artifact@v4
        with:
          name: results_component_tests
          path: automated_testing/component_tests/results

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Analyse component tests results and write results to scoreboard files
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/component_tests/analysis_scripts')
            analyse_component_tests('${{github.workspace}}/automated_testing')

      - name: Upload scoreboard files as artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: scoreboard_files_component_tests
          path: automated_testing/scoreboard/temporary_scoreboard_files/*.xml
