# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated_tests/idealised/ISMIP-HOM
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated_tests/idealised/ISMIP-HOM
on:
  workflow_call:

jobs:
  ISMIP-HOM:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --remote

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_perf_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_10_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_10_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_10_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_10_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_10_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_10_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_160_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_160_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_160_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_160_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_160_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_160_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_20_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_20_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_20_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_20_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_20_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_20_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_40_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_40_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_40_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_40_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_40_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_40_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_5_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_5_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_5_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_5_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_5_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_5_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_80_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_80_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_80_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_80_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_A_80_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_A_80_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_10_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_10_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_10_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_10_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_10_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_10_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_160_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_160_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_160_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_160_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_160_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_160_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_20_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_20_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_20_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_20_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_20_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_20_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_40_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_40_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_40_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_40_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_40_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_40_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_5_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_5_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_5_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_5_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_5_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_5_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_80_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_80_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_80_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_80_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_B_80_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_B_80_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_10_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_10_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_10_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_10_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_10_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_10_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_160_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_160_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_160_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_160_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_160_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_160_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_20_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_20_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_20_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_20_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_20_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_20_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_40_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_40_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_40_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_40_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_40_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_40_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_5_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_5_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_5_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_5_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_5_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_5_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_80_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_80_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_80_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_80_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_C_80_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_C_80_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_10_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_10_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_10_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_10_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_10_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_10_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_160_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_160_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_160_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_160_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_160_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_160_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_20_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_20_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_20_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_20_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_20_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_20_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_40_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_40_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_40_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_40_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_40_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_40_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_5_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_5_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_5_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_5_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_5_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_5_SIASSA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_80_BPA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_80_BPA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_80_DIVA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_80_DIVA.cfg

      - name: Run integrated_tests/idealised/ISMIP-HOM - ISMIP_HOM_D_80_SIASSA
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/ISMIP-HOM/config_ISMIP_HOM_D_80_SIASSA.cfg

      - name: Analyse integrated_tests/idealised/ISMIP-HOM
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/integrated_tests/idealised/ISMIP-HOM')
            analyse_integrated_test('${{github.workspace}}/automated_testing')

      - name: Upload scoreboard file as artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: scoreboard_file_integrated_tests_idealised_ISMIP-HOM
          path: automated_testing/scoreboard/temporary_scoreboard_files/*.xml
