# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km
on:
  workflow_call:

jobs:
  Ant_init_20kyr_invBMB_invfric_40km:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --remote

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_perf_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km/config.cfg

      - name: Analyse integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/integrated_tests/realistic/Antarctica/initialisation/Ant_init_20kyr_invBMB_invfric_40km')
            analyse_integrated_test('${{github.workspace}}/automated_testing')

      - name: Upload scoreboard file as artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: scoreboard_file_integrated_tests_realistic_Antarctica_initialisation_Ant_init_20kyr_invBMB_invfric_40km
          path: automated_testing/scoreboard/temporary_scoreboard_files/*.xml
