# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated_tests/idealised/MISMIPplus
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated_tests/idealised/MISMIPplus
on:
  workflow_call:

jobs:
  MISMIPplus:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/python/requirements.txt

      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          repository: 'IMAU-paleo/data'
          path: 'data'

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_perf_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated_tests/idealised/MISMIPplus - 01_5km_spinup_part0
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_01_5km_spinup_part0.cfg

      - name: Run integrated_tests/idealised/MISMIPplus - 02_5km_spinup
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_02_5km_spinup.cfg

      - name: Run integrated_tests/idealised/MISMIPplus - 03_5km_ice1r
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_03_5km_ice1r.cfg

      - name: Run integrated_tests/idealised/MISMIPplus - 04_4km_spinup
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_04_4km_spinup.cfg

      - name: Run integrated_tests/idealised/MISMIPplus - 05_4km_ice1r
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_05_4km_ice1r.cfg

      - name: Run integrated_tests/idealised/MISMIPplus - 06_5km_iceocean1r
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/MISMIPplus/config_06_5km_iceocean1r.cfg

      - name: Analyse integrated_tests/idealised/MISMIPplus
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/integrated_tests/idealised/MISMIPplus')
            analyse_integrated_test('${{github.workspace}}/automated_testing')

      - name: Analyse integrated_tests/idealised/MISMIPplus/MISOMIP
        run: python automated_testing/integrated_tests/idealised/MISMIPplus/analyse_integrated_test_misomip.py ${{github.workspace}}/automated_testing

      - name: Upload scoreboard file as artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: scoreboard_file_integrated_tests_idealised_MISMIPplus
          path: automated_testing/scoreboard/temporary_scoreboard_files/*.xml
